### PR TITLE
Issues #1 - #19 (without the EMTech Header)

### LINKED ISSUE #1: Create landing page view for 'Components > Buttons'
We need to create the 'Components > Buttons' landing page that will display the buttons for both MP Cloud and EMTech Billing.

**Blockers**
- None

**Acceptance Criteria**
1. We can navigate to this page via the main nav; [like in the Nine Labs Design System](https://designsystem.ninelabs.com/component-buttons.html)
2. Page has H1 and leading copy that we reuse from [like at the top of the Buttons page in the Nine Labs Design System](https://designsystem.ninelabs.com/component-buttons.html).
    Example of screenshot:
    image

### LINKED ISSUE #2: Create sections for buttons on the 'Components > Buttons' landing page view
We need to create sections on the 'Components > Buttons' landing page view for both MP Cloud and EMTech Billing buttons.

### Blocker
This is a blocker for #1 

### Acceptance Criteria

1. We can navigate to this page via the main nav; [like in the Nine Labs Design System](https://designsystem.ninelabs.com/component-buttons.html)

2. There is a section (with a side nav anchor link) labeled **MP Cloud Buttons** with the following groupings/ headings and examples ([from the UI Inventory](https://ninelabs.invisionapp.com/console/MP-Cloud-&-EMTech---UI-Inventory-ckr2qrwri05u501tpa624381i/ckr2qrzji049f01zv6ufgbsps/play))

      **[NOTE]:** The "Leading Content Block Buttons" are the same for both MP Cloud and EMTech Billing. Hopefully, you will have to swap out the background gradient used in the examples._

image

3. There is a section (with a side nav anchor link) labeled **EMTech Buttons** with the following groupings/ headings and examples ([from the UI Inventory](https://ninelabs.invisionapp.com/console/MP-Cloud-&-EMTech---UI-Inventory-ckr2qrwri05u501tpa624381i/ckr2qrzji049k01zv5ccm8mk1/play))

image

### LINKED ISSUE #3: Create sections for chips on the 'Components > Chips' landing page view
We need to create sections on the 'Components > Chips' landing page view for both MP Cloud and EMTech Billing chips.

### Blocker
Issues -- #5, #4

### Acceptance Criteria

1. We can navigate to this page via the main nav; [like in the Nine Labs Design System](https://designsystem.ninelabs.com/component-buttons.html)

2. There is a section (with a side nav anchor link) labeled **MP Cloud Chips** with the following groupings/ headings and examples ([from the UI Inventory](https://ninelabs.invisionapp.com/console/MP-Cloud-&-EMTech---UI-Inventory-ckr2qrwri05u501tpa624381i/ckr2qrzji049f01zv6ufgbsps/play))

      **[NOTE]:** The "Chips" are the same for both MP Cloud and EMTech Billing -- aside from single variant for EMTech Billing._

image

3. There is a section (with a side nav anchor link) labeled **EMTech Chips** with the following groupings/ headings and examples ([from the UI Inventory](https://ninelabs.invisionapp.com/console/MP-Cloud-&-EMTech---UI-Inventory-ckr2qrwri05u501tpa624381i/ckr2qrzji049k01zv5ccm8mk1/play))

image

### LINKED ISSUE #4: Create landing page view for 'Components > Chips'
We need to create the 'Components > Buttons' landing page that will display the buttons for both MP Cloud and EMTech Billing.

**Blockers**
- None

**Acceptance Criteria**

1. We can navigate to this page via the main nav; [like in the Nine Labs Design System](https://designsystem.ninelabs.com/component-buttons.html)
2. Page has H1 labeled "Chips" (without any follow up paragraph copy at this time)

### LINKED ISSUE #5: Create landing page view for 'Components > Icons'
We need to create the 'Components > Icons' landing page that will display the icons for both MP Cloud and EMTech Billing.

**Blockers**
1. Cleo has to create and attached the icon font assets (font files and CSS) for both MP Cloud and EMTech Billing.
2. Then this can be started and will unblock -- #3

**Acceptance Criteria**

1. We can navigate to this page via the main nav; [like in the Nine Labs Design System](https://designsystem.ninelabs.com/component-buttons.html)
2. Page has H1 labeled "Icons" (without any follow up paragraph copy at this time)

### LINKED ISSUE #6: Create sections for icons on the 'Components > Icons' landing page view
We need to create sections on the 'Components > Icons' landing page view for both MP Cloud and EMTech Billing icons.

### Blocker
Issues -- #5

### Acceptance Criteria

1. We can navigate to this page via the main nav; [like in the Nine Labs Design System](https://designsystem.ninelabs.com/component-buttons.html)

2. There is a section (with a side nav anchor link) labeled **MP Cloud Icon Font** with the following groupings/ headings and examples ([from the UI Inventory](https://ninelabs.invisionapp.com/console/MP-Cloud-&-EMTech---UI-Inventory-ckr2qrwri05u501tpa624381i/ckr2qrzji049f01zv6ufgbsps/play))

image

3. There is a section (with a side nav anchor link) labeled **EMTech  Icon Font** with the following groupings/ headings and examples ([from the UI Inventory](https://ninelabs.invisionapp.com/console/MP-Cloud-&-EMTech---UI-Inventory-ckr2qrwri05u501tpa624381i/ckr2qrzji049k01zv5ccm8mk1/play))

image

### LINKED ISSUE #8: Create landing page view for 'Components > Footer'
We need to create the 'Components > Footer' landing page that will display all footer related components for both MP Cloud and EMTech Billing.

**Blockers**
1. None

**Acceptance Criteria**

1. We can navigate to this page via the main nav; [like in the Nine Labs Design System](https://designsystem.ninelabs.com/component-buttons.html)
2. Page has H1 labeled "Footer" (without any follow up paragraph copy at this time)

### LINKED ISSUE #9: Create section for 'Pre-Footer Content Block' on the 'Components > Footer' landing page view
We need to create sections on the 'Components > Footer' landing page view for the MP Cloud Pre-Footer Content Block.

### Blocker
Issues -- #8

### Acceptance Criteria

1. We can navigate to this page via the main nav; [like in the Nine Labs Design System](https://designsystem.ninelabs.com/component-buttons.html)

2. There is a section (with a side nav anchor link) labeled **MP Pre-Footer Content Block** withOUT the following groupings/ headings ([from the UI Inventory](https://ninelabs.invisionapp.com/console/MP-Cloud-&-EMTech---UI-Inventory-ckr2qrwri05u501tpa624381i/ckr2qrzji049g01zvc9ze9i4l/play))

image

3. There is a 4px (or .25rem) white `<hr>` element at the top of the component with "white bolts" on the left and right ends (see below). Assets have been attached as a PNG and SVG for you to see which one renders best. 

image
[PreFooter Assets.zip](https://github.com/ninelabs/mpcloud-design-system/files/6910359/PreFooter.Assets.zip)

### LINKED ISSUE #10: Create section for 'Pre-Footer Callout Block' on the 'Components > Footer' landing page view
We need to create sections on the 'Components > Footer' landing page view for both MP Cloud and EMTech Billing Pre-Footer Callout Block.

### Blocker
Issues -- #8, #11, #12 

### Acceptance Criteria

1. We can navigate to this page via the main nav; [like in the Nine Labs Design System](https://designsystem.ninelabs.com/component-buttons.html)

2. There is a section (with a side nav anchor link) labeled **MP Pre-Footer Callout Block** ([from the UI Inventory](image))

image

3. There is a section (with a side nav anchor link) labeled **EMTech Pre-Footer Callout Block** withOUT the following groupings/ headings ([from the UI Inventory](image))

image

### LINKED ISSUE #12: Create section on the 'Images' landing page view
We need to create sections on the 'Images' landing page view for both MP Cloud and EMTech Billing Stock Photography.

### Blocker
Issues -- #11 

### Acceptance Criteria

1. We can navigate to this page via the main nav; [like in the Nine Labs Design System](https://designsystem.ninelabs.com/component-buttons.html)

2. There is a section (with a side nav anchor link) labeled **Stock Photography** ([from the UI Inventory](https://ninelabs.invisionapp.com/console/MP-Cloud-&-EMTech---UI-Inventory-ckr2qrwri05u501tpa624381i/ckrr7bbgc0dps01zp8kfhgiiw/play)). Here are the [stock images](https://www.dropbox.com/s/u7yscv3iy1hn61n/Stock%20Photography.zip?dl=0)

image

### PR DESCRIPTION
**Pull request by radoslaw-1**
Work In Progress

### CODE REVIEW

**Comment by radoslaw-1** [comment]
@cleezy @jcornelius 

I've started the development process, but there are a few questions I wanted to ask before moving further:

1. Can I place the components from the same section next to each other instead of creating subsections? In other words, do components like the MP Cloud Primary Buttons need the Large and the Regular subsections or would `MP Cloud Buttons > Primary Button` be enough for both of them? Screenshot of the current structure for reference:

Screenshot from 2021-07-28 16-04-03

2. Is the way I create new classes correct? What should I do if there are new colors? I had to add `#6C7075`, which I temporarily named `$gray-light-2`, because I wasn't sure if it should overwrite the original `$gray-light` variable.

3. Are there different states for the components in the InVision docs? I was wondering about the implementation of focus and hover states for the new buttons.

4. Should the `Leading Content Block Buttons` component be an updated version of the Bootstrap carousel? If so, its content would be a div with text, wouldn't it? And where can I get the arrow icons used in this component from so I can replace the regular Bootstrap ones?

**Comment by cleezy** [comment]
Only documenting the answers to the questions via a Slack chat...

1. ‘MP Cloud Buttons > Primary Button’ works just fine.
2. Make the [grays from EMTech](https://ninelabs.invisionapp.com/console/MP-Cloud--EMTech---UI-Inventory-ckr2qrwri05u501tpa624381i/ckr2qrzji049j01zvh1dj34e4/play) ‘$emt-gray-…’ and follow the same pattern for ‘$emt-orange’ and ‘$emt-blue’. For MP Cloud make the colors ‘$mp-blue-..’ and  ‘$pulse-red-..’ and  ‘$cloud-blue-..’. The reason is because ‘gray, blue, etc…’ are base names for colors that each brand may have a variant of in the future. This will keep things separated.
3. [I updated the UI Inventory](https://ninelabs.invisionapp.com/console/MP-Cloud--EMTech---UI-Inventory-ckr2qrwri05u501tpa624381i/ckr2qrzji049f01zv6ufgbsps/play)
4. Yes, an updated variant of the bootstrap component. Yes, its content would be a div with text.[ Here are the Icon fonts and CSS for both brands](https://www.dropbox.com/s/t2oi0lrhb99wu4s/emtechandmpcloudIcons-v1.0.zip?dl=0) (and also attached).

[emtechandmpcloudIcons-v1.0.zip](https://github.com/ninelabs/mpcloud-design-system/files/6910118/emtechandmpcloudIcons-v1.0.zip)

**Comment by cleezy** [comment]
@radoslaw-1 installed this icon font set instead. There's a play icon for the video player example which we will need very soon in a different enhancement.
[emtechandmpcloudIcons-v1.0 (1).zip](https://github.com/ninelabs/mpcloud-design-system/files/6910281/emtechandmpcloudIcons-v1.0.1.zip)

**Comment by radoslaw-1** [comment]
@cleezy I've added the Icons, but the EMTech Card Asset Chip turned out to be quite problematic. I did some research and I can't think of a solution that isn't overcomplicated (like adding extra markup for all the circles that create the round border). The fact that this component's background uses the alpha channel adds to the complexity of this implementation.

Why don't we just create a partially transparent SVG that becomes the background for Card Asset components? It could simply look like this:
image
What are your thoughts on this?

All the other components from issues #1 - #6 are ready to be reviewed. Should I remove the `WIP` from the task name and work on the Card Asset on a different branch once we decide on the best approach?

**Comment by radoslaw-1** [comment]
@cleezy FYI, I'm using the same branch for the new issues because the components there use some of the things that have been created in #1 - #6 (the buttons, for example).

**Comment by radoslaw-1** [comment]
@cleezy I've just added the MP Cloud Pre-Footer Accordion Block and the MP Cloud/EMTech Billing Footers. I couldn't find the caret icon used in the Accordion Block, so I temporarily replaced it with the mathematical operator "or". Please note that because of the `docs-subnav`, the footers may not look too good locally (they are not wide enough). You can remove `docs-content`'s `max-width` using the DevTools to see how they should look like.

**Comment by cleezy** [comment]
> @cleezy I've added the Icons, but the EMTech Card Asset Chip turned out to be quite problematic. I did some research and I can't think of a solution that isn't overcomplicated (like adding extra markup for all the circles that create the round border). The fact that this component's background uses the alpha channel adds to the complexity of this implementation.
> 
> Why don't we just create a partially transparent SVG that becomes the background for Card Asset components? It could simply look like this:
> image
> What are your thoughts on this?
> 
> All the other components from issues #1 - #6 are ready to be reviewed. Should I remove the `WIP` from the task name and work on the Card Asset on a different branch once we decide on the best approach?

@radoslaw-1 I like the idea and attached the SVG for you.
[card-assest-chip-border-emt.svg.zip](https://github.com/ninelabs/mpcloud-design-system/files/6932100/card-assest-chip-border-emt.svg.zip)

**Comment by cleezy** [comment]
> @cleezy I've just added the MP Cloud Pre-Footer Accordion Block and the MP Cloud/EMTech Billing Footers. I couldn't find the caret icon used in the Accordion Block, so I temporarily replaced it with the mathematical operator "or". Please note that because of the `docs-subnav`, the footers may not look too good locally (they are not wide enough). You can remove `docs-content`'s `max-width` using the DevTools to see how they should look like.

@radoslaw-1 
Here's an updated Icon Font with icons and CSS for:
- menu, close, chevron-up, chevron-right, chevron-left, chevron-down
image

[emtechandmpcloudIcons-v1.3.zip](https://github.com/ninelabs/mpcloud-design-system/files/6932213/emtechandmpcloudIcons-v1.3.zip)

**Comment by radoslaw-1** [comment]
Please keep in mind that because of the `docs-content`'s `max-width`, the MP Cloud Header doesn't take up the whole page width.

**Pull request merged**
